name: Docker Image Security Scan

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "docker/**"

jobs:
  validate:
    name: Validate Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: "chrisherrera1/swish-analytics"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker image
        run: |
          cd docker/
          docker build -f Dockerfile --no-cache -t $IMAGE_NAME:${{ github.sha }} .
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'